channels:
  - conda-forge
dependencies:
  - qgis=3.18
  - websockify
  - kaleido-core
  - plotly
  - pandas
  - numpy
  - scikit-learn
  - scipy
  - chart-studio
  - openpyxl
  - pyppeteer
  - pip
  - pyqt
  - pip:
      - jupyter-remote-desktop-proxy